export const getFileTypes = (ext: string): [string, string] => {
  const types: Record<string, [string, string]> = {
    xlsx: ["fa fa-file-excel-o", "green"],
    xls: ["fa fa-file-excel-o", "green"],
    xlsm: ["fa fa-file-excel-o", "green"],
    zip: ["fa fa-file-archive-o", "orange"],
    rar: ["fa fa-file-archive-o", "orange"],
    "7zip": ["fa fa-file-archive-o", "orange"],
    doc: ["fa fa-file-word-o", "blue"],
    docx: ["fa fa-file-word-o", "blue"],
    pptx: ["fa fa-file-powerpoint-o", "red"],
    mp3: ["fa fa-file-sound-o", "blue"],
    wav: ["fa fa-file-sound-o", "blue"],
    m4a: ["fa fa-file-sound-o", "blue"],
    mp4: ["fa fa-file-video-o", "blue"],
    mov: ["fa fa-file-video-o", "blue"],
    avi: ["fa fa-file-video-o", "blue"],
    wmv: ["fa fa-file-video-o", "blue"],
    flv: ["fa fa-file-video-o", "blue"],
    "3gp": ["fa fa-file-video-o", "blue"],
    png: ["fa fa-file-picture-o", "black"],
    jpg: ["fa fa-file-picture-o", "black"],
    ico: ["fa fa-file-picture-o", "black"],
    gif: ["fa fa-file-picture-o", "black"],
    jpeg: ["fa fa-file-picture-o", "black"],
    svg: ["fa fa-file-picture-o", "black"],
    pdf: ["fa fa-file-pdf-o", "red"],
    css: ["fa fa-file-code-o", "black"],
    html: ["fa fa-file-code-o", "black"],
    cs: ["fa fa-file-code-o", "black"],
    txt: ["fa fa-file-text-o", "blue"],
  };
  return types[ext] || ["fa fa-file", "black"];
};